version: "3.1"

services:
  db:
    image: postgres
    restart: always
    volumes:
      - ./dbvolume:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: botion
      POSTGRES_PASSWORD: botion
      POSTGRES_DB: botion

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
